version: "3"
services:
  proxy:
    #build: ./
    image: zterry95/shadowsocks-client-python
    container_name: ss_proxy_python
    volumes:
      - ./shadowsocks.json:/etc/shadowsocks.json
    ports:
      - "2080:1080"
